//send data all users
GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

//create users
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "salman alfarisi",
    "email": "salman@gmail.com",
    "gender": "Male"
}

//method update
###
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "alfarisi",
    "email": "alfarisi@gmail.com",
    "gender": "Male"
}

//method hapus
###
DELETE  http://localhost:5000/users/1

